version: '3'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./bin:/app/bin
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - 3000:3000
